#!/bin/bash

# Définir les chemins vers les vidéos
video1="video/video1.mp4"
video2="video/video2.mp4"
video3="video/video3.mp4"
video4="video/video4.mp4"

# Lire la première vidéo par défaut
omxplayer $video1 &

# Boucle d'écoute pour les boutons
while true; do
  # Lire la vidéo 1 si BTN_TRIGGER est appuyé
  if [ "$(evtest /dev/input/event4)" == "1" ]; then
    pkill omxplayer
    omxplayer $video1 &
  fi

  # Lire la vidéo 2 si BTN_THUMB est appuyé
  if [ "$(evtest /dev/input/event4)" == "1" ]; then
    pkill omxplayer
    omxplayer $video2 &
  fi

  # Lire la vidéo 3 si BTN_THUMB2 est appuyé
  if [ "$(evtest /dev/input/event4)" == "1" ]; then
    pkill omxplayer
    omxplayer $video3 &
  fi

  # Lire la vidéo 4 si BTN_TOP est appuyé
  if [ "$(evtest /dev/input/event4)" == "1" ]; then
    pkill omxplayer
    omxplayer $video4 &
  fi
done