#!/bin/bash

# Bouton A
bind '"\x01\x00\x00\x00"' "omxplayer -o hdmi video/video1.mp4"

# Bouton B
bind '"\x02\x00\x00\x00"' "omxplayer -o hdmi video/video2.mp4"

# Bouton X
bind '"\x03\x00\x00\x00"' "omxplayer -o hdmi video/video3.mp4"

# Bouton Y
bind '"\x04\x00\x00\x00"' "omxplayer -o hdmi video/video4.mp4"
