#!/bin/bash

jstest /dev/input/js0

while true; do
  button_state=$(jstest /dev/input/js0 | grep BTN_TRIGGER | awk '{print $3}')
  if [ "$button_state" == "1" ]; then
    omxplayer -o hdmi video1.mp4
  fi
  button_state=$(jstest /dev/input/js0 | grep BTN_THUMB | awk '{print $3}')
  if [ "$button_state" == "1" ]; then
    omxplayer -o hdmi video2.mp4
  fi
  button_state=$(jstest /dev/input/js0 | grep BTN_THUMB2 | awk '{print $3}')
  if [ "$button_state" == "1" ]; then
    omxplayer -o hdmi video3.mp4
  fi
  button_state=$(jstest /dev/input/js0 | grep BTN_TOP | awk '{print $3}')
  if [ "$button_state" == "1" ]; then
    omxplayer -o hdmi video4.mp4
  fi
done